# Generated by Django 4.1 on 2024-03-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inspire", "0003_downloadserviceentryfeed_servicefeed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetservicefeed",
            name="self_link",
        ),
        migrations.RemoveField(
            model_name="downloadserviceentryfeed",
            name="self_link",
        ),
    ]
