# Generated by Django 4.1 on 2024-03-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inspire", "0004_remove_datasetservicefeed_self_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadserviceentryfeed",
            name="opensearch_link",
        ),
    ]
