# Generated by Django 4.1 on 2024-03-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspire", "0005_remove_downloadserviceentryfeed_opensearch_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetservicefeed",
            name="available_crs",
            field=models.ManyToManyField(to="inspire.crs"),
        ),
    ]
